function fireNetSeerTrigger(){window.netseer_fire_on_trigger=null;netseerMainFunction(window)}
function netseerMainFunction(e){function u(a,b){var d=new Image;y+1<z.length&&(d.onload=function(){u(a,b)},d.onerror=function(){u(a,b)},d.onabort=function(){u(a,b)});var g="",c="",f=z[y++];e.netseer_cookie&&(g="&cookie=0");31===f&&(c="&ui=2");d.src=39===f?function(){var a=r(window)+"cmi.netseer.com/pixelmatch?ex=39&xid=__UID__&t="+A,a=encodeURIComponent(a),b="ssum";"https://"===r(window)&&(b="ssum-sec");return r(window)+b+".casalemedia.com/usermatchredir?s=183876&cb="+a}():r(window)+"cmi.netseer.com/redirect?ex="+
f+"&t="+A+g+c}function D(a,b,d){var g="";d&&(g=new Date,g.setDate(g.getDate()+d),g="; expires="+g.toUTCString());document.cookie=a+"="+b+g+"; path=/"}function E(a){a+="=";for(var b=document.cookie.split(";"),d=0;d<b.length;d++){for(var g=b[d];" "==g.charAt(0);)g=g.substring(1,g.length);if(0==g.indexOf(a))return g.substring(a.length,g.length)}return null}function B(a,b){a=String(a);var d=new RegExp("\\?"+b+"=[^&]*&?","gi");a=a.replace(d,"?");d=new RegExp("\\&"+b+"=[^&]*&?","gi");a=a.replace(d,"&");
return a=a.replace(/(\?|&)$/,"")}function p(a,b,d,g){null==d&&(d="");null==g&&(g="&");a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");a=(new RegExp("[\\?"+g+"]"+a+"=([^"+g+"#]*)")).exec(b);return null==a?d:a[1]}function r(a){var b="http://";a&&a.location&&a.location.protocol&&"https:"==a.location.protocol.toString().toLowerCase()?b="https://":a&&a.netseer_enforce_protocol&&"https"==a.netseer_enforce_protocol?b="https://":a&&a.netseer_page_url&&"https"==a.netseer_page_url.toLowerCase().substring(0,
5)?b="https://":!a||"1"!=a.netseer_ssl&&"true"!=a.netseer_ssl||(b="https://");return b}function v(a){var b=r(a);a.netseer_endpoint?"contextlinks.netseer.com"==a.netseer_endpoint?a.netseer_endpoint="cl.netseer.com":"staging.netseer.com"==a.netseer_endpoint&&(a.netseer_endpoint="media.netseer.com"):a.netseer_endpoint=a&&"px"==a.netseer_task?"pixel.netseer.com":"cl.netseer.com";return b+a.netseer_endpoint}function m(a){return null!=a?'"'+a+'"':'""'}function k(a,b){if(a){b&&(a=a.replace(/\+/g," "));try{return"function"==
typeof decodeURIComponent?decodeURIComponent(a):unescape(a)}catch(d){return""}}else return a}function c(a,b){if(b){var d="&";e.netseer_global_fparam&&"true"==e.netseer_global_fparam&&(d="");e.netseer_ad_url+=d+a+"="+b;e.netseer_global_fparam="false"}}function w(a,b){b&&(e.netseer_page_params&&""!=e.netseer_page_params&&(e.netseer_page_params+="&"),e.netseer_page_params+=a+"="+b)}function h(a,b){if(b){var d;if(b)try{d="function"==typeof encodeURIComponent?encodeURIComponent(b):escape(b)}catch(g){d=
""}else d=b;c(a,d)}}function F(a,b,d,g,c,f,h,e,l,k,r,p,t,q,n){g=Math.random();c=c.substring(0,2083);c=c.replace(/%\w?$/,"");null!=c&&(c=c+"&t="+g);"lp"==a?(b='<iframe  id="netseer_landingpage_frame"  name="netseer_landingpage_frame" width='+m(d)+" height="+m(b)+" src="+m(c)+' frameborder="0" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no"></iframe>',document.getElementById(f).innerHTML=b):"ad"==a?(a=document,q&&"dfp_outofpage"===q?a=window.parent.document:
q&&"iframe_buster"===q&&(a=window.parent.parent.document),q=a.getElementById(f),t&&"js"==t?(b=document.createElement("script"),b.type="text/javascript",b.async=!0,b.src=c,q&&q.appendChild(b)):(b='<iframe name="netseer_ads_frame" width='+m(d)+" height="+m(b)+" src="+m(c)+' frameborder="0" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no"></iframe>',q&&(q.innerHTML=b)),b=E("netseer_cm"),"false"!=r&&"done"!=b&&!h&&"10"!=e&&(null==n||isNaN(parseInt(n))||100>
parseInt(n))&&(u(e),"11"!=e&&"12"!=e&&"13"!=e&&"14"!=e&&"15"!=e&&"16"!=e&&"17"!=e&&"18"!=e&&"20"!=e&&"21"!=e&&"27"!=e&&D("netseer_cm","done",15))):"px"==a&&(p&&"sync"==p?C(c,l,k,f,e):G(function(){C(c,l,k,f,e)}))}function G(a){function b(){d||(d=!0,a())}var d=!1;if("complete"===document.readyState||"interactive"===document.readyState)b();else if(window.addEventListener)window.addEventListener("load",b,!1);else if(document.addEventListener)document.addEventListener("DOMContentLoaded",b,!1);else if(document.attachEvent){try{var c=
null!=window.frameElement}catch(e){}if(document.documentElement.doScroll&&!c){var f=function(){if(!d)try{document.documentElement.doScroll("left"),b()}catch(a){setTimeout(f,10)}};f()}document.attachEvent("onreadystatechange",function(){"complete"===document.readyState&&b()})}}function C(a,b,d,c,e){var f=new Image;f.onload=function(){u(e,c)};f.onerror=function(){u(e,c)};f.onabort=function(){u(e,c)};f.src=a;"undefined"!=typeof b&&H(b,d,c)}function H(a,b,d){a='<iframe name="nspx" width=0 height=0 src='+
m(b+"/dsatserving2/servlet/pixel?pxid="+a)+' frameborder="0" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no"></iframe>';(b=document.getElementById(d))?b.innerHTML=a:(b=document.createElement("ins"),b.style.cssText="display:inline-table;border:none;height:0;width:0;;margin:0;padding:0;position:relative;visibility:hidden",b.setAttribute("id",d),b.innerHTML=a,document.documentElement.lastChild.appendChild(b))}function I(a){(new Date).getTime();a.netseer_page_params=
"";a.netseer_global_fparam="true";if(a.netseer_redundant_params)for(var b=a.netseer_redundant_params.split(","),d=0;d<b.length;d++)a.netseer_page_url=B(a.netseer_page_url,b[d]);a.netseer_url_pattern&&(b=(new RegExp(a.netseer_url_pattern,"gi")).exec(a.netseer_page_url),null!=b&&(a.netseer_page_url=k(b[1])));b=a.netseer_page_url;if("lp"==a.netseer_task)a.netseer_ad_url=v(a)+"/dsatserving2/servlet/search?",(d=a.location.search.substring(1))&&(d=d.replace("tlid=","tlidr=")),p("tlid",d,null,null),c("tlid",
a.netseer_is_inview?a.netseer_inview_taglink_id:a.netseer_taglink_id),d&&(e.netseer_ad_url+="&"+d),h("url",b);else if("ad"==a.netseer_task){a.netseer_ad_url=v(a)+"/dsatserving2/servlet/BannerServer?";a.netseer_ad_endpoint&&(a.netseer_ad_url=r(a)+a.netseer_ad_endpoint,a.netseer_ad_url+="?nlt=AD_REQUEST&");c("tagid",a.netseer_tag_id);c("tlid",a.netseer_is_inview?a.netseer_inview_taglink_id:a.netseer_taglink_id);c("cid",a.netseer_creative_id);c("cptgid",a.netseer_concept_group_id);c("plid",a.netseer_pilot_id);
c("rlid",a.netseer_rule_id);c("utgid",a.netseer_user_tgid);c("ptgid",a.netseer_page_tgid);c("ucgid",a.netseer_user_cgid);c("pcgid",a.netseer_page_cgid);c("bft",a.netseer_back_fill);if(null==a.netseer_iframe_buster||""==a.netseer_iframe_buster){if(a.netseer_image_src_url){var d=a.netseer_image_src_url,g=0;if(0!=d.length)for(i=0;i<d.length;i++)g=(g<<5)-g+d.charCodeAt(i),g&=g;d=g;b=B(b,"nspid");b=b+"&nspid="+d;/\?/.test(b)||(b=b.replace(/&/,"?"))}h("url",b)}c("q",a.netseer_query)}else"px"==a.netseer_task&&
(a.netseer_ad_url=v(a)+"/dsatserving2/servlet/log?",c("tagid",a.netseer_tag_id),c("tlid",a.netseer_is_inview?a.netseer_inview_taglink_id:a.netseer_taglink_id),c("pxid",a.netseer_pixel_id),a.netseer_log_type||(a.netseer_log_type="ltpx"),c("nlt",a.netseer_log_type),c("cid",a.netseer_creative_id),c("q",a.netseer_query),h("url",b),h("pxp1",a.netseer_pixel_param1),h("pxp2",a.netseer_pixel_param2),h("pxp3",a.netseer_pixel_param3),h("pxcpa",a.netseer_pixel_cpa));c("thid",a.netseer_theme_id);c("adh",a.netseer_ad_height);
c("adw",a.netseer_ad_width);c("imps",a.netseer_imp_src);c("impt",a.netseer_imp_type);c("pp",a.netseer_pcpm);c("auid",a.netseer_auction_id);c("sidx",a.netseer_slot_index);for(b=0;b<t.length;b++)null!=a[t[b]]&&c(J[b],a[t[b]]);for(b=0;b<n.length;b++)null!=a[n[b]]&&h(K[b],a[n[b]]);h("rfd",a.netseer_referrer_domain);c("evid",a.netseer_ext_vid);w("segment",a.netseer_segment);w("sites",a.netseer_recirculation_sites);w("bingformc",a.netseer_bing_formcode);if(b=a.netseer_ext_params)e.netseer_page_params+=
"&"+b;h("nslp",k(a.netseer_lead_params));c("bp",a.netseer_bcpm);a.netseer_cookie&&c("cookie","0");h("sep",a.netseer_search_param);h("set",k(a.netseer_search_term,!0));h("trurl",k(a.netseer_tracking_url));c("advs",a.netseer_advs);h("rfs",k(a.netseer_referrer_search_term,!0));c("frd",a.netseer_first_request_date);c("ip",a.netseer_ip);c("cnads",a.netseer_num_ads);c("adpos",a.netseer_ad_position);c("cpc",a.netseer_cpc);c("cimg",a.netseer_image_size);c("cimgfrc",a.netseer_image_forced);a.netseer_image_sizeon&&
c("imgsizeon",a.netseer_image_sizeon);h("hints",a.netseer_hints);h("extsct",k(a.netseer_ext_script));h("inimgmv",k(a.netseer_image_meta_val));h("inimga",k(a.netseer_img_alt));h("inimgu",k(a.netseer_image_src_url));c("rclid",a.netseer_referred_client_id);c("acdt",a.netseer_search_time);c("engt",a.netseer_engine_type);c("flowid",a.netseer_flow_id);c("pgv_id",a.netseer_pgv_id);c("apid",a.netseer_append_location);a.netseer_embed_style&&"js"==a.netseer_embed_style&&c("sid",a.netseer_append_location);a.netseer_referrer_url&&
2E3>a.netseer_ad_url.length+a.netseer_referrer_url.length&&h("ref",k(a.netseer_referrer_url));h("params",a.netseer_page_params);F(a.netseer_task,a.netseer_ad_height,a.netseer_ad_width,a.netseer_iframe_buster,a.netseer_ad_url,a.netseer_append_location,a.netseer_cookie,a.netseer_imp_src,a.netseer_pixel_id,v(a),a.netseer_cookie_matching,a.netseer_pixel_trigger_mode,a.netseer_embed_style,a.netseer_deployment_type,a.netseer_imp_type);a.netseer_global_fparam=null;a.netseer_query=null;a.netseer_ad_frameborder=
null;a.netseer_ad_format=null;a.netseer_page_url=null;a.netseer_output_format=null;a.netseer_language=null;a.netseer_gl=null;a.netseer_hints=null;a.netseer_safe=null;a.netseer_encoding=null;a.netseer_ad_output=null;a.netseer_max_num_ads=null;a.netseer_ad_channel=null;a.netseer_contents=null;a.netseer_adtest=null;a.netseer_kw_type=null;a.netseer_kw=null;a.netseer_num_radlinks=null;a.netseer_max_radlink_len=null;a.netseer_rl_filtering=null;a.netseer_rl_mode=null;a.netseer_rt=null;a.netseer_ad_type=
null;a.netseer_image_size=null;a.netseer_skip=null;a.netseer_page_location=null;a.netseer_referrer_url=null;a.netseer_ad_region=null;a.netseer_ad_section=null;a.netseer_bid=null;a.netseer_cpa_choice=null;a.netseer_cust_age=null;a.netseer_cust_gender=null;a.netseer_cust_interests=null;a.netseer_cust_id=null;a.netseer_cust_job=null;a.netseer_cust_u_url=null;a.netseer_sim=null;a.netseer_color_bilboard=null;a.netseer_banner_id=null;a.netseer_network_id=null;a.netseer_tracking_url=null;a.netseer_tracking_url_encoded=
null;a.netseer_page_url_key=null;a.netseer_search_current_url=null;a.netseer_page_params=null;a.netseer_page_url_base64=null;a.netseer_landing_page_type=null;a.netseer_background_color=null;a.netseer_click_target=null;a.netseer_pixel_param1=null;a.netseer_pixel_param2=null;a.netseer_pixel_param3=null;a.netseer_pixel_id=null;a.netseer_tag_id=null;a.netseer_client_id=null;a.netseer_task=null;a.netseer_creative_id=null;a.netseer_auction_id=null;a.netseer_slot_index=null;a.netseer_imp_type=null;a.netseer_ext_vid=
null;a.netseer_advs=null;a.netseer_taglink_id=null;a.netseer_inview_taglink_id=null;a.netseer_segment=null;a.netseer_iframe_buster=null;a.netseer_search_param=null;a.netseer_recirculation_sites=null;a.netseer_fire_on_trigger=null;a.netseer_redundant_params=null;a.netseer_url_pattern=null;a.netseer_theme_id=null;a.netseer_imp_src=null;a.netseer_endpoint=null;a.netseer_ad_height=null;a.netseer_ad_width=null;a.netseer_page_url_key=null;a.netseer_debug=null;a.netseer_pixel_cpa=null;a.netseer_search_term=
null;a.netseer_visitor_cookie=null;a.netseer_cookie=null;a.netseer_hints=null;a.netseer_bing_formcode=null;a.netseer_embed_external_pixels=null;a.netseer_referrer_search_term=null;a.netseer_referrer_domain=null;a.netseer_concept_group_id=null;a.netseer_ext_params=null;a.netseer_url_suffix=null;a.netseer_embed_style=null;a.netseer_append=null;a.netseer_pilot_id=null;a.netseer_rule_id=null;a.netseer_enforce_protocol=null;a.netseer_lead_params=null;a.netseer_ip=null;a.netseer_num_ads=null;a.netseer_ad_position=
null;a.netseer_cpc=null;a.netseer_user_tgid=null;a.netseer_page_tgid=null;a.netseer_user_cgid=null;a.netseer_page_cgid=null;a.netseer_image_size=null;a.netseer_image_forced=null;a.netseer_cookie_matching=null;a.netseer_req_id=null;a.netseer_ext_script=null;a.netseer_pixel_trigger_mode=null;a.netseer_back_fill=null;a.netseer_referred_client_id=null;a.netseer_search_time=null;a.netseer_engine_type=null;a.netseer_flow_id=null;for(b=0;b<t.length;b++)a[t[b]]=null;for(b=0;b<n.length;b++)a[n[b]]=null}function x(a,
b){return b&&a?-1!=b.indexOf(a):!1}function L(a){var b=document,d=b.location,c=b.referrer;null==a.netseer_first_request_date&&(a.netseer_first_request_date=(new Date).getTime());a.netseer_search_current_url=d;var e=null;a.netseer_referrer_url&&(e=a.netseer_referrer_url);c&&(a.netseer_tag_id&&17744==a.netseer_tag_id&&(a.netseer_page_url=c),e||(e=c));if(e)try{a.netseer_referrer_domain=e.split("/")[2];c=e;e=null;if(x(".google.",c))e=p("q",c,null);else if(x(".bing.",c))e=p("q",c,null);else if(x(".yahoo.",
c)){var f=p("p",c,null);if(f)e=f;else{var h=p("q",c,null);h&&(e=h)}}e&&(e=e.replace(/\+/g," "));a.netseer_referrer_search_term=e}catch(m){}document.cookie="testcookie";cookieBlocked=-1!=document.cookie.indexOf("testcookie")?!1:!0;document.cookie="testcookie; expires=Thu, 01 Jan 1970 00:00:01 GMT;";f=navigator.userAgent.toLowerCase();f=-1!=f.indexOf("safari")&&-1==f.indexOf("chrom")?"Safari":-1!=f.indexOf("mozilla/5.0 (windows nt 6.1; wow64; trident/7.0; rv:11.0) like gecko")?"IE11NoCookie":-1!=f.indexOf("opera")?
"Opera":-1!=f.indexOf("staroffice")?"Star Office":-1!=f.indexOf("webtv")?"WebTV":-1!=f.indexOf("beonex")?"Beonex":-1!=f.indexOf("chimera")?"Chimera":-1!=f.indexOf("netpositive")?"NetPositive":-1!=f.indexOf("phoenix")?"Phoenix":-1!=f.indexOf("firefox")?"Firefox":-1!=f.indexOf("skipstone")?"SkipStone":-1!=f.indexOf("msie")?"Internet Explorer":-1!=f.indexOf("netscape")?"Netscape":-1!=f.indexOf("mozilla/5.0")?"Mozilla":-1!=f.indexOf("/")?"mozilla"!=f.substr(0,f.indexOf("/"))?navigator.userAgent.substr(0,
f.indexOf("/")):"Netscape":-1!=f.indexOf(" ")?navigator.userAgent.substr(0,f.indexOf(" ")):navigator.userAgent;0!=cookieBlocked||"Safari"!=f&&"IE11NoCookie"!=f||(cookieBlocked=!0);a.netseer_cookie=cookieBlocked;if(null==a.netseer_page_url){var l;d=a.netseer_page_url_key;if(null==d)try{l=a.top.location.href}catch(n){l=a.location.href}else l=d.split(","),d="&",3<l.length&&(d=l[3]),d=k(p(l[0],a.location,null,d)),1<l.length&&(d=l[1]+d),2<l.length&&(d+=l[2]),l=d;a.netseer_page_url=l;a.netseer_last_modified_time=
Date.parse(b.lastModified)/1E3}else a.netseer_page_location=d,a.netseer_page_url=k(a.netseer_page_url);a.netseer_url_suffix&&(a.netseer_page_url+=a.netseer_url_suffix)}var t="netseer_ssl netseer_carrier_id netseer_lat netseer_long netseer_country netseer_city netseer_zip netseer_region netseer_dma netseer_device_type netseer_platform netseer_handset_id netseer_connection netseer_device_id netseer_site_id netseer_app_id netseer_ext_channel netseer_aud_segment netseer_demo netseer_inv_type netseer_req_id netseer_pgv_id netseer_seller_id netseer_debug".split(" "),
J="ssl caid lat long cntr city zip rgn metro dvtype plf hsid cnn dvid stid appid extch extaseg demo invtype refid exsid dbg".split(" "),n=["netseer_site_name","netseer_app_name"],K=["stname","appname"],A=(new Date).getHours(),z=[10,11,14,16,27,18,31,39],y=0;window.injectNetseerAd=function(a,b){var c=document.getElementById(a),e='<iframe  id="nsfiframe_'+a+'"  name="netseer_friendly_frame" width='+m(netseer_ad_width)+" height="+m(netseer_ad_height)+' frameborder="0" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no"></iframe>',
h=document.createElement("ins");h.innerHTML=e;c.appendChild(h);iFrame=h.getElementsByTagName("iframe")[0];iFrame.contentDocument.open();iFrame.contentDocument.write(b);iFrame.contentDocument.close()};e.netseer_fire_on_trigger||(L(e),I(e))};
